services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - db
    command: >
      /bin/sh -c '
      npx prisma db push &&
      npm run start'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume: